"""empty message

Revision ID: 9fdb714ebacf
Revises: 168be2bf4711
Create Date: 2024-08-01 12:00:07.378741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fdb714ebacf'
down_revision = '168be2bf4711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_recebido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_recebimento', sa.DateTime(), nullable=True),
    sa.Column('descricao_produto', sa.String(), nullable=True),
    sa.Column('recebido_por', sa.String(), nullable=False),
    sa.Column('registrado_por', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material_recebido')
    # ### end Alembic commands ###
