"""empty message

Revision ID: aa0476ccec4e
Revises: 71bc8f83d7b3
Create Date: 2024-08-07 21:35:27.239141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0476ccec4e'
down_revision = '71bc8f83d7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_movimentacao', schema=None) as batch_op:
        batch_op.alter_column('destino',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('movimentado_por',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_movimentacao', schema=None) as batch_op:
        batch_op.alter_column('data_movimentacao',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('movimentado_por',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('destino',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
